language: python
dist: xenial
python:
  - 3.5
  - 3.7

addons:
  apt:
    packages:
    - enchant
    - aspell-ar
    - aspell-bn
    - myspell-cs
    - aspell-de
    - myspell-es
    - myspell-en-au
    - myspell-en-gb
    - myspell-en-us
    - myspell-en-za
    - aspell-et
    - aspell-el
    - myspell-fa
    - myspell-fr
    - myspell-he
    - myspell-hr
    - aspell-hi
    - aspell-hu
    - aspell-id
    - myspell-it
    - myspell-nb
    - aspell-nl
    - aspell-pl
    - aspell-sv
    - myspell-pt
    - aspell-ro
    - aspell-ru
    - aspell-ta
    - aspell-uk
    - hunspell-bs
    - hunspell-vi
    - hunspell-sr
    - myspell-lv
    - aspell-is
    - myspell-ca
    - hunspell-gl

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -r docs/requirements.txt
  - pip install -r test-requirements.txt
  - python setup.py install
  - pip install twine
  - python -m nltk.downloader stopwords

script:
  - flake8 . --max-line-length=85 --exclude docs/conf.py
  - coverage run --source editquality -m pytest -m "not nottravis"
  - sphinx-build -anW -b html docs dist/docs
  - sphinx-build -b linkcheck docs dist/docs

after_success:
  - coverage report
  - codecov

notifications:
  irc:
    channels:
      - "chat.freenode.net#wikimedia-ai"
    on_success: change
    on_failure: change
    template:
      - "%{repository_slug}#%{build_number} (%{branch} - %{commit} : %{author}): %{message} %{build_url}"

#deploy:
#  provider: script
#  script: bash scripts/deploy.sh
#  on:
#    branch: master
